//===----------------------------------------------------------------------===//
// Copyright (c) 2020 Athena. All rights reserved.
// https://getathena.ml
//
// Licensed under MIT license.
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations under
// the License.
//===----------------------------------------------------------------------===//

// fixme this file should be autogenerated.

#ifndef ATHENA_PROGRAMDESC_H
#define ATHENA_PROGRAMDESC_H

#include <map>
#include <string>
#include <vector>

namespace athena::backend::llvm {
struct KernelDesc {
  size_t globalX;
  size_t globalY;
  size_t globalZ;
  size_t localX;
  size_t localY;
  size_t localZ;
};
struct ProgramDesc {
  enum class Type { PTX, SPIRV_SHADER };

  Type type;
  std::string target;
  std::vector<char> data;
  std::map<std::string, KernelDesc> kernels;
};
} // namespace athena::backend::llvm

#endif // ATHENA_PROGRAMDESC_H
