//===----------------------------------------------------------------------===//
// Copyright (c) 2020 PolarAI. All rights reserved.
//
// Licensed under MIT license.
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations under
// the License.
//===----------------------------------------------------------------------===//

// fixme this file should be autogenerated.

#pragma once

#include <cstdint>

struct ArgDesc {
  enum ArgType { TENSOR = 0, DATA = 1 };
  uint64_t size;
  void* arg;
  ArgType type;
};

struct LaunchCommand {
  const char* kernelName;
  uint64_t argsCount;
  ArgDesc* args;
  const char* nativeKernelName;
};
